---
openapi: 3.0.0
info:
  title: Personal Blog Api
  description: A API to serve a simple blog
  version: "1.0"
servers:
- url: https://virtserver.swaggerhub.com/RODRIGODSBECKMANN/personal-blog-api/1.0
  description: SwaggerHub API Auto Mocking
paths:
  /login:
    post:
      description: Return a token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login_body'
      responses:
        "200":
          description: Succesfully return a token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "422":
          description: If user does not enter email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
        "401":
          description: If email or password not match with user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
components:
  schemas:
    Schema:
      type: object
      properties:
        id:
          type: integer
          format: int64
    Schema1:
      type: object
      properties:
        id:
          type: integer
          format: int64
    login_body:
      type: object
      properties:
        email:
          type: string
          example: user@email.com
        password:
          type: string
          example: "123456"
    inline_response_200:
      type: object
      properties:
        token:
          type: string
          description: user token
    inline_response_422:
      type: object
      properties:
        message:
          type: string
          example: Some required fields are missing
    inline_response_401:
      type: object
      properties:
        message:
          type: string
          example: Incorrect username or password
