version: '3'

services:
  node:
    build: .
    user: node
    container_name: personal-blog-api
    tty: true
    stdin_open: true
    command: ash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: database
      PORT: 3001

  database:
    image: mysql:8.0.29
    container_name: personal-blog-db
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: personal-blog-db
    volumes:
      - ./:/docker-entrypoint-initdb.d
